name = "CoralbloxCf"
uuid = "ef92c705-1aee-4282-9a5f-fa2e6f5cb888"
authors = ["Peter Baker <peter.baker122@csiro.au>"]
version = "0.1.0"

[deps]
ADRIA = "7dc409a7-fbe5-4c9d-b3e2-b0c19a6ba600"
AWS = "fbe9abb3-538b-5e4e-ba9e-bc94f4f92ebc"
AWSS3 = "1c724243-ef5b-51ab-93f4-b0a88ac62a95"
ArchGDAL = "c9ce4bd3-c3d5-55b8-8973-c0e20141b8c3"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DotEnv = "4dc1fcf4-5e3b-5448-94ab-0c38ec0385c1"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Zarr = "0a941bbe-ad1d-11e8-39d9-ab76183a1d99"

[compat]
ADRIA = "0.11.0"
AWS = "^1"
AWSS3 = "^0"
ArchGDAL = "0.10.8"
CSV = "0.10.15"
DataFrames = "1.7.0"
DotEnv = "1.0.0"
JSON = "0.21.4"
JSON3 = "1.14.2"
Random = "1.11.0"
Zarr = "0.9.4"
